### ISSUE TITLE
Possible memory leak during ZStream consumption

### ISSUE THREAD

**Issue by myazinn** [zio/zio-kafka#485]
Here's a repository that contains a reproduction code.
https://github.com/myazinn/zio-kafka-bug-demo
Unfortunately, I couldn't minimise it more and had to use embedded Kafka for reproduction.

This repo contains 2 branches: `main` with ZIO 2 implementation and `zio-1` with ZIO 1 implementation (see details below).

In this example, I just add a lot of messages to Kafka (~1 million) and then read them without doing anything (hence `runDrain`). It appears something is keeping all read elements in memory, which eventually causes `java.lang.OutOfMemoryError: Java heap space` error.

Here's what happens when I run `KafkaApp` with `-Xmx700m` VM option (could be any number actually as long as there's enough messages to pollute the memory).
```SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Produced 110000 messages
Produced 220000 messages
Produced 330000 messages
Produced 440000 messages
Produced 550000 messages
Produced 660000 messages
Produced 770000 messages
Produced 880000 messages
Produced 990000 messages
Produced 1100000 messages
Consumed 110000 messages
Consumed 220000 messages
Consumed 330000 messages
Consumed 440000 messages
Consumed 550000 messages
Consumed 660000 messages
Consumed 770000 messages
Consumed 880000 messages
java.lang.OutOfMemoryError: Java heap space
 at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:61)
 at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:348)
 at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
 at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:113)
 at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
 at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
 at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
 at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
 at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
 at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560)
 at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
 at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
 at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1306)
 at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1242)
 at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1215)
 at zio.kafka.consumer.internal.Runloop.doPoll(Runloop.scala:282)
 at zio.kafka.consumer.internal.Runloop.$anonfun$handlePoll$3(Runloop.scala:304)
 at zio.kafka.consumer.internal.Runloop$$Lambda$2328/0x0000000800a2c840.apply(Unknown Source)
 at zio.ZIO$.$anonfun$suspend$1(ZIO.scala:4319)
 at zio.ZIO$$$Lambda$2312/0x0000000800a23040.apply(Unknown Source)
 at zio.FiberRef$unsafe$$anon$2.$anonfun$getWith$1(FiberRef.scala:447)
 at zio.FiberRef$unsafe$$anon$2$$Lambda$252/0x000000080023e040.apply(Unknown Source)
 at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:966)
 at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:931)
 at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
 at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
 at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:324)
 at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:447)
 at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:217)
 at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

VisualVM shows that heap usage dramatically increases right after consumption process begins.
![telegram-cloud-document-2-5361922590635989887](https://user-images.githubusercontent.com/28982711/178523135-bcfc0b62-b0d5-4cb0-944a-f96b261dc7d9.jpg)

For comparison, here's what happens when I rewrite the same code to ZIO 1. 
![telegram-cloud-document-2-5361922590635989890](https://user-images.githubusercontent.com/28982711/178523341-afa333fc-2003-4fc9-a1f1-f636422aa122.jpg)

I tried to rollback `2.0.0` version to use `3.1.0` Kafka client instead of `3.2.0`, but it didn't help.
I also tried to reproduce it with vanilla ZIO streams or dummy `zio.kafka.consumer.Consumer` which `partitionStream` method generates values itself, but in both cases I couldn't reproduce an issue, that's why I had to use embedded Kafka. Though maybe it's possible to reproduce an issue without Kafka instance, I just couldn't find a way to do it.

**Comment by adwells-ds** [comment]
Additionally checked with standalone kafka and older versions (down to 2.0.0-M1). The issue persists for all 2.x versions.
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/87975016/178682595-3e86eb06-e9fe-496b-b691-325f0aea5026.png">

**Comment by guizmaii** [comment]
Is this happening with `zio1` version? 🤔

**Comment by myazinn** [comment]
@guizmaii nope, latest `zio-kafka` with `zio1` version (`0.17.5`) works fine
https://github.com/myazinn/zio-kafka-bug-demo/tree/zio-1

**Comment by vigoo** [comment]
I will try to take a look later this week

**Comment by narma** [comment]
I looked at diff v0.17.5 (unaffected, latest on zio-1) ... v2.0.0-M1 (first on zio-2) and it only contains migrations, nothing significant has been added, changed or deleted. This sounds like an issue with zio2.

**Comment by vigoo** [comment]
Yes it's very likely a bug in the new zio streams implementation.

**Comment by guizmaii** [comment]
Should be fixed in the new 2.0.1 release, no? 🤔

**Comment by 987Nabil** [comment]
I updated to ZIO `2.0.1` and the leak persists. I don't think it's fixed.

**Comment by 987Nabil** [comment]
I came up with a temp fix in our applications like this

```scala
    ZIO.raceFirst(
		consumerEffect,
      	ZIO.unit.delay(5.minutes) :: Nil,
    ).forever
```

**But be careful!**
This kills the `consumerEffect` maybe at a time it should not be killed. If you are not idempotent you might want to think about using `ZIO#uninterruptible` to define when not to kill the effect.

**Comment by erikvanoosten** [comment]
I am analyzing a memory dump of a process that went OOM, probably because of this issue. We see that most of the heap is used by instances of `org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch`. These objects are used by the Kafka consumer and contain the consumed messages from Kafka.

We did many experiments and saw the following:
* When handling messages in a straight stream (e.g. no methods like `mapZIOPar` or `aggregateAsync`) and from 2 topics only, throughput is limited to ~200 msg/s and we see no OOM.
* As soon we make it more efficient with `mapZIOPar` and `aggregateAsync` (reaching 4K msg/s), OR increase the number of topics (to our target number of ~3000), we see an OOM within 10 or 2 minutes respectively.

From this we tentatively conclude that our app lacks back pressure to the consumer; the ZIO stream is pulling more from the Kafka consumer than it needs.

Unfortunately we don't have the expertise to debug ZIO streams so for now we are going to rewrite our app to ZIO 1.

**Comment by adamgfraser** [comment]
We are working on this!

**Comment by erikvanoosten** [comment]
@adamgfraser I tried our application with a snapshot of ZIO at commit https://github.com/zio/zio/commit/813a8313f64861f43199daf75b018ec23ec41b1e which is the merge commit of PR https://github.com/zio/zio/pull/7256. Other Zio jars were kept at 2.0.1.

Our application now only needs 32 seconds to create an OOM. Strangly enough, the heap had only grown to 640Mb yet while the max is set to 4Gb. The application only just started consuming. Something strange is going on here. I will investigate further.

**Comment by ya-goodfella** [comment]
> @adamgfraser I tried our application with a snapshot of ZIO at commit [zio/zio@813a831](https://github.com/zio/zio/commit/813a8313f64861f43199daf75b018ec23ec41b1e) which is the merge commit of PR [zio/zio#7256](https://github.com/zio/zio/pull/7256). Other Zio jars were kept at 2.0.1.

This sounds a bit vague. Can you please elaborate which jars you have updated and why you don't keep versions of zio artifacts synchronized?

By the way, last Adam's fix affected both `zio` and `zio-streams`.

**Comment by erikvanoosten** [comment]
> This sounds a bit vague. Can you please elaborate which jars you have updated and why you don't keep versions of zio artifacts synchronized?

I build a snapshot for `"dev.zio" %% "zio"`. The 'other' zio jars are `"dev.zio" %% "zio-internal-macros"` and `"dev.zio" %% "zio-stacktracer"`.

I was under the impression that zio-streams is completely bundled up in `"dev.zio" %% "zio"`. Is that not the case?

**Comment by erikvanoosten** [comment]
> I was under the impression that zio-streams is completely bundled up in `"dev.zio" %% "zio"`. Is that not the case?

Oops, that is not the case. Okay, back to testing...

**Comment by ya-goodfella** [comment]
> > This sounds a bit vague. Can you please elaborate which jars you have updated and why you don't keep versions of zio artifacts synchronized?
> 
> I build a snapshot for `"dev.zio" %% "zio"`. The 'other' zio jars are `"dev.zio" %% "zio-internal-macros"` and `"dev.zio" %% "zio-stacktracer"`.
> 
> I was under the impression that zio-streams is completely bundled up in `"dev.zio" %% "zio"`. Is that not the case?

Personally, I would recommend to use snapshot versions published on Sonatype and keep versions synchronized as much as possible.

**Comment by erikvanoosten** [comment]
> Personally, I would recommend to use snapshot versions published on Sonatype and keep versions synchronized as much as possible.

Thanks for the tip, I didn't know those are available.

**Comment by erikvanoosten** [comment]
I tried again this morning with ZIO 2.0.2 and we see a huge memory usage improvement. It now runs fine when consuming 2 topics. However, with 3000 topics our zio-kafka application still goes OOM quite quickly.

**Comment by adamgfraser** [comment]
Okay, well that's something. Can you create a minimized reproducer? Since multiple other users reported this fix working for them your problem may be different than the original issue.

**Comment by erikvanoosten** [comment]
> Can you create a minimized reproducer?

Since our problem seems to depend on the number of topics, I am not sure how to approach this. I'll keep it in mind though, any help to solve this is appreciated :)

**Comment by adwells-ds** [comment]
Can you share the setup, with the default settings(i.e. 2 prefetch polls and 500 records batch) and all active topics/partitions you will have at least 3\*500\*3000(4.5kk) records per time, plus the gc will need time to cleanup all those records, so it could lead to 100's kk of records sitting in memory for intensive workloads

Also if you have single partition per topic and using the default partitioner, all partition_nr0 will also be placed only on the single instance of the application, even if you using multiple instances(in this case you need to use RoundRobin partitioner or other strategies to balance the load)

**Comment by erikvanoosten** [comment]
Thanks @adwells-ds . I was suspecting something like that. We are indeed using the default settings. After increasing the heap from 4Gib to 20Gib we can easily handle 500 topics so that cofirms your comment. 3000 topics is still too much (didn't check between those yet).

Can we somehow limit zio-kafka from pre-fetching so much data? I guess we could lower the number of prefetch polls to 1 (or to 0?), but I am afraid it will affect throughput too much.

**Comment by erikvanoosten** [comment]
Anyways, it seems my problem is not related to this issue. I propose that this issue is closed.

**Comment by adwells-ds** [comment]
> Can we somehow limit zio-kafka from pre-fetching so much data? I guess we could lower the number of prefetch polls to 1 (or to 0?), but I am afraid it will affect throughput too much.

if you reduce the prefetch to 0, it would mean, that you just have to wait for the network I/O to load new batch(for local network should be fine - assuming network latency < 1ms), also you always can reduce the batch size, it will put a bit more pressure on kafka nodes and network, but should reduce the memory consumption

**Comment by adamgfraser** [comment]
Going to close this as multiple users have reported that this been resolved for them and it appears that any remaining issues are unrelated. However, there is definitely significant complexity here between ZIO, ZIO Stream, and ZIO Kafka so if anyone does have another problem with excessive memory consumption feel free to open a new issue.

**Comment by erikvanoosten** [comment]
For those that are curious about our OOM problems: we accidentally had Kafka settings that are meant for consuming over the internet (higher `fetch.min.bytes` and `max.partition.fetch.bytes`). After reverting these to the defaults, and using `ConsumerSettings(...).withPerPartitionChunkPrefetch(-1)`, memory usage stayed below 5GiB while consuming from almost 3000 topics. The fixes from ZIO 2.0.2 are also needed.

One interesting bit is that using `withPerPartitionChunkPrefetch(-1)` does not seem to affect throughput much compared to the default of 2. Perhaps this is only true for a high number of topics.

**Comment by adamgfraser** [comment]
Great news! Thanks for the update!

**Comment by svroonland** [comment]
Likely also improved by https://github.com/zio/zio/pull/7603
